-- Migration to add LessonPlan table
CREATE TABLE `LessonPlan` (
	`lesson_plan_id` bigint AUTO_INCREMENT NOT NULL,
	`entry_id` bigint NOT NULL,
	`user_id` bigint NOT NULL,
	`date` date NOT NULL,
	`start_time` varchar(50),
	`end_time` varchar(50),
	`sector` varchar(100),
	`trade` varchar(100),
	`level` int,
	`module_code` varchar(50),
	`module_name` varchar(255),
	`no_trainees` int,
	`class_name` varchar(100),
	`learning_outcomes` text,
	`indicative_content` text,
	`topic_big_question` text,
	`range_duration` varchar(100),
	`objectives` text,
	`language_focus` text,
	`facilitation_techniques` text,
	`specific_knowledge` text,
	`introduction_trainer` text,
	`introduction_learner` text,
	`introduction_resources` text,
	`introduction_duration` varchar(50),
	`development_trainer` text,
	`development_learner` text,
	`development_resources` text,
	`development_duration` varchar(50),
	`conclusion_summary` text,
	`conclusion_learner` text,
	`conclusion_duration` varchar(50),
	`assignment` text,
	`evaluation` text,
	`references` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `LessonPlan_lesson_plan_id` PRIMARY KEY(`lesson_plan_id`)
);

ALTER TABLE `LessonPlan` ADD CONSTRAINT `LessonPlan_entry_id_SchemeOfWorkEntry_entry_id_fk` FOREIGN KEY (`entry_id`) REFERENCES `SchemeOfWorkEntry`(`entry_id`) ON DELETE cascade ON UPDATE no action;
ALTER TABLE `LessonPlan` ADD CONSTRAINT `LessonPlan_user_id_User_user_id_fk` FOREIGN KEY (`user_id`) REFERENCES `User`(`user_id`) ON DELETE no action ON UPDATE no action;
