/**
 * Static permission constants for backend access control
 * These match the permissions stored in the database
 */
export const Permissions = {
  // User management
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_USERS: "VIEW_USERS",
  ENABLE_DISABLE_USERS: "ENABLE_DISABLE_USERS",
  CHANGE_USER_ROLES: "CHANGE_USER_ROLES",
  MANAGE_PROGRAM_LEADS: "MANAGE_PROGRAM_LEADS",
  UPDATE_USER_PROFILE_INFO: "UPDATE_USER_PROFILE_INFO",

  // Role & Permission management
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",

  // Academic management
  MANAGE_ACADEMICS: "MANAGE_ACADEMICS",
  VIEW_ACADEMICS: "VIEW_ACADEMICS",

  // Class management
  MANAGE_CLASSES: "MANAGE_CLASSES",
  VIEW_CLASSES: "VIEW_CLASSES",

  // Student management
  MANAGE_STUDENTS: "MANAGE_STUDENTS",
  VIEW_STUDENTS: "VIEW_STUDENTS",
  MANAGE_STUDENT_ENROLLMENTS: "MANAGE_STUDENT_ENROLLMENTS",
  ASSIGN_STUDENT_CLASS_GROUPS: "ASSIGN_STUDENT_CLASS_GROUPS",
  VIEW_SUBJECT_ENROLLED_STUDENTS: "VIEW_SUBJECT_ENROLLED_STUDENTS",

  // Teacher management
  MANAGE_TEACHERS: "MANAGE_TEACHERS",
  VIEW_TEACHERS: "VIEW_TEACHERS",
  VIEW_MY_ASSIGNED_SUBJECTS: "VIEW_MY_ASSIGNED_SUBJECTS",
  VIEW_MY_STUDENTS: "VIEW_MY_STUDENTS",
  TEACHER_DASHBOARD: "TEACHER_DASHBOARD",
  ASSIGN_TEACHER_SUBJECTS: "ASSIGN_TEACHER_SUBJECTS",

  // Parent management
  MANAGE_PARENTS: "MANAGE_PARENTS",
  VIEW_PARENTS: "VIEW_PARENTS",

  // Grades & Results
  MANAGE_GRADES: "MANAGE_GRADES",
  VIEW_GRADES: "VIEW_GRADES",

  // Attendance
  MANAGE_ATTENDANCE: "MANAGE_ATTENDANCE",
  VIEW_ATTENDANCE: "VIEW_ATTENDANCE",

  // Reports
  VIEW_REPORTS: "VIEW_REPORTS",
  GENERATE_REPORTS: "GENERATE_REPORTS",
  ACCESS_REPORT_CARD_MODULE: "ACCESS_REPORT_CARD_MODULE",

  // Marks/Results
  ENTER_MARKS: "ENTER_MARKS",
  VIEW_RESULTS: "VIEW_RESULTS",

  // Announcements & Documents
  SEND_ANNOUNCEMENTS: "SEND_ANNOUNCEMENTS",
  UPLOAD_DOCUMENTS: "UPLOAD_DOCUMENTS",

  // System settings
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  MANAGE_SCHOOLS: "MANAGE_SCHOOLS",
  MANAGE_SYSTEMS: "MANAGE_SYSTEMS",
  ASSIGN_SCHOOL_SYSTEMS: "ASSIGN_SCHOOL_SYSTEMS",

  // Admin
  ADMIN: "ADMIN",

  // Program Management
  VIEW_PROGRAM_USERS: "VIEW_PROGRAM_USERS",
  VIEW_PROGRAM_ACADEMICS: "VIEW_PROGRAM_ACADEMICS",

  // Class Teacher Management
  ASSIGN_GRADE_TO_CLASS_TEACHER: "ASSIGN_GRADE_TO_CLASS_TEACHER",
  VIEW_USERS_BY_CLASS_TEACHER_GRADE: "VIEW_USERS_BY_CLASS_TEACHER_GRADE",
  VIEW_SUBJECTS_BY_CLASS_TEACHER_GRADE: "VIEW_SUBJECTS_BY_CLASS_TEACHER_GRADE",

  // SSO Management
  MANAGE_SSO_CLIENTS: "MANAGE_SSO_CLIENTS",

  // Academic Calendar Management
  MANAGE_ACADEMIC_CALENDAR: "MANAGE_ACADEMIC_CALENDAR",
  CREATE_ACADEMIC_CALENDAR: "CREATE_ACADEMIC_CALENDAR",
  UPDATE_CALENDAR_SLOT: "UPDATE_CALENDAR_SLOT",
  VIEW_ACADEMIC_CALENDAR: "VIEW_ACADEMIC_CALENDAR",
  MANAGE_CALENDAR_NOTIFICATIONS: "MANAGE_CALENDAR_NOTIFICATIONS",
  VIEW_CALENDAR_NOTIFICATIONS: "VIEW_CALENDAR_NOTIFICATIONS",
  VIEW_MY_CALENDAR: "VIEW_MY_CALENDAR",
  VIEW_LESSON_PLANS: "VIEW_LESSON_PLANS",
  VIEW_STUDENT_CALENDAR: "VIEW_STUDENT_CALENDAR",

  // Logs Management
  VIEW_ALL_LOGS_HISTORY: "VIEW_ALL_LOGS_HISTORY",

  // Scheme of Work Management
  VIEW_ALL_TEACHERS_SCHEME_OF_WORK_LIST: "VIEW_ALL_TEACHERS_SCHEME_OF_WORK_LIST",
  VALIDATE_SCHEME_OF_WORK: "VALIDATE_SCHEME_OF_WORK",

  // Reporting
  SUBMIT_REPORTING: "SUBMIT_REPORTING",
  /** @deprecated use VIEW_REPORTS / EXPORT_REPORTS / MANAGE_REPORTS instead
   * (Phase 6 permission split) — kept as an OR-fallback in route guards for
   * one release cycle so no existing admin loses access on cutover. */
  ALL_SUBMITTED_REPORTS: "ALL_SUBMITTED_REPORTS",
  EXPORT_REPORTS: "EXPORT_REPORTS",
  MANAGE_REPORTS: "MANAGE_REPORTS",

  // Mentorship
  MANAGE_MENTOR_ASSIGNMENTS: "MANAGE_MENTOR_ASSIGNMENTS",
  SUBMIT_MENTEE_CHECKIN: "SUBMIT_MENTEE_CHECKIN",

  // Curriculum & Subject Materials
  MANAGE_CURRICULUM: "MANAGE_CURRICULUM",
  UPLOAD_SUBJECT_DOCUMENTS: "UPLOAD_SUBJECT_DOCUMENTS",
  VIEW_SUBJECT_DOCUMENTS: "VIEW_SUBJECT_DOCUMENTS",
  DOWNLOAD_SUBJECT_DOCUMENTS: "DOWNLOAD_SUBJECT_DOCUMENTS",
  VIEW_MY_ENROLLED_SUBJECTS: "VIEW_MY_ENROLLED_SUBJECTS",

  // Lesson Notes
  MANAGE_LESSON_NOTES: "MANAGE_LESSON_NOTES",
  VIEW_SHARED_LESSON_NOTES: "VIEW_SHARED_LESSON_NOTES",

  // E-Learning
  MANAGE_COURSE_CONTENT: "MANAGE_COURSE_CONTENT",
  VIEW_MY_COURSES: "VIEW_MY_COURSES",
  VIEW_ALL_COURSES: "VIEW_ALL_COURSES",
  OVERRIDE_COURSE_PROGRESS: "OVERRIDE_COURSE_PROGRESS",

  // Office hours (OFFICE_HOURS_IMPLEMENTATION_PLAN.md §15)
  OFFICE_HOURS_MANAGE_OWN: "OFFICE_HOURS_MANAGE_OWN",
  OFFICE_HOURS_MANAGE_ANY: "OFFICE_HOURS_MANAGE_ANY",
  OFFICE_HOURS_VIEW: "OFFICE_HOURS_VIEW",
  OFFICE_HOURS_VIEW_SELF: "OFFICE_HOURS_VIEW_SELF",
  OFFICE_HOURS_CONFIGURE: "OFFICE_HOURS_CONFIGURE",

  // Database Management
  DATABASE_MANAGEMENT: "DATABASE_MANAGEMENT",
} as const;

/**
 * Helper to get all permissions for SUPER_ADMIN role
 */
export const ALL_PERMISSIONS = Object.values(Permissions);
