/**
 * Static permission constants for backend access control
 * These match the permissions stored in the database
 */
export const Permissions = {
  // User management
  MANAGE_USERS: "MANAGE_USERS",
  VIEW_USERS: "VIEW_USERS",
  ENABLE_DISABLE_USERS: "ENABLE_DISABLE_USERS",
  CHANGE_USER_ROLES: "CHANGE_USER_ROLES",
  MANAGE_PROGRAM_LEADS: "MANAGE_PROGRAM_LEADS",
  UPDATE_USER_PROFILE_INFO: "UPDATE_USER_PROFILE_INFO",

  // Role & Permission management
  MANAGE_ROLES: "MANAGE_ROLES",
  MANAGE_PERMISSIONS: "MANAGE_PERMISSIONS",

  // Academic management
  MANAGE_ACADEMICS: "MANAGE_ACADEMICS",
  VIEW_ACADEMICS: "VIEW_ACADEMICS",

  // Class management
  MANAGE_CLASSES: "MANAGE_CLASSES",
  VIEW_CLASSES: "VIEW_CLASSES",

  // Student management
  MANAGE_STUDENTS: "MANAGE_STUDENTS",
  VIEW_STUDENTS: "VIEW_STUDENTS",
  MANAGE_STUDENT_ENROLLMENTS: "MANAGE_STUDENT_ENROLLMENTS",
  ASSIGN_STUDENT_CLASS_GROUPS: "ASSIGN_STUDENT_CLASS_GROUPS",

  // Teacher management
  MANAGE_TEACHERS: "MANAGE_TEACHERS",
  VIEW_TEACHERS: "VIEW_TEACHERS",
  VIEW_MY_ASSIGNED_SUBJECTS: "VIEW_MY_ASSIGNED_SUBJECTS",
  TEACHER_DASHBOARD: "TEACHER_DASHBOARD",
  ASSIGN_TEACHER_SUBJECTS: "ASSIGN_TEACHER_SUBJECTS",

  // Parent management
  MANAGE_PARENTS: "MANAGE_PARENTS",
  VIEW_PARENTS: "VIEW_PARENTS",

  // Grades & Results
  MANAGE_GRADES: "MANAGE_GRADES",
  VIEW_GRADES: "VIEW_GRADES",

  // Attendance
  MANAGE_ATTENDANCE: "MANAGE_ATTENDANCE",
  VIEW_ATTENDANCE: "VIEW_ATTENDANCE",

  // Reports
  VIEW_REPORTS: "VIEW_REPORTS",
  GENERATE_REPORTS: "GENERATE_REPORTS",
  ACCESS_REPORT_CARD_MODULE: "ACCESS_REPORT_CARD_MODULE",

  // Marks/Results
  ENTER_MARKS: "ENTER_MARKS",
  VIEW_RESULTS: "VIEW_RESULTS",

  // Announcements & Documents
  SEND_ANNOUNCEMENTS: "SEND_ANNOUNCEMENTS",
  UPLOAD_DOCUMENTS: "UPLOAD_DOCUMENTS",

  // System settings
  MANAGE_SETTINGS: "MANAGE_SETTINGS",
  MANAGE_SCHOOLS: "MANAGE_SCHOOLS",
  MANAGE_SYSTEMS: "MANAGE_SYSTEMS",
  ASSIGN_SCHOOL_SYSTEMS: "ASSIGN_SCHOOL_SYSTEMS",

  // Admin
  ADMIN: "ADMIN",

  // Program Management
  VIEW_PROGRAM_USERS: "VIEW_PROGRAM_USERS",
  VIEW_PROGRAM_ACADEMICS: "VIEW_PROGRAM_ACADEMICS",

  // Class Teacher Management
  ASSIGN_GRADE_TO_CLASS_TEACHER: "ASSIGN_GRADE_TO_CLASS_TEACHER",
  VIEW_USERS_BY_CLASS_TEACHER_GRADE: "VIEW_USERS_BY_CLASS_TEACHER_GRADE",
  VIEW_SUBJECTS_BY_CLASS_TEACHER_GRADE: "VIEW_SUBJECTS_BY_CLASS_TEACHER_GRADE",
} as const;

/**
 * Helper to get all permissions for SUPER_ADMIN role
 */
export const ALL_PERMISSIONS = Object.values(Permissions);
